(ns acme.state
  (:require ["package:flutter/material.dart" :as m]))

;; FONTS

(def numeric-font "CourierPrimeSans")
(def default-font "Montserrat")
(def cabacus-font "Gaegu")

;; COLORS

; Nice place to look for colors: https://colorcodes.io/
(def colors
  (-> {:amber m.Colors/amber
       :wood (m/Color.fromARGB 255 164 116 73)
       :blue-grey m.Colors/blueGrey
       :grey m.Colors/grey
       :light-blue-accent m.Colors/lightBlueAccent
       :purple-accent m.Colors/purpleAccent
       :light-green m.Colors/lightGreen
       :dark-blue (m/Color.fromARGB 255 21 96 189)
       :blue m/Colors.lightBlue
       :red m/Colors.red
       :pink (m/Color.fromARGB 255 255 62 165)
       :orange m/Colors.orange
       :turquoise (m/Color.fromARGB 255 83 176 174)}
      (update-vals
       (fn [seed-color]
         {:seed-color seed-color
          :color-scheme (m/ColorScheme.fromSeed .seedColor seed-color)}))))

;; STYLE

(def frame-width 6)

(def bead-style-ratios {:narrow 3/2 :wide 5/3})

;; SIZES

(def sizes-base {:small  {:height 36 :rod-width 12}
                 :medium {:height 42 :rod-width 14}
                 :large  {:height 48 :rod-width 16}})

;; SPEED

(def speeds {:slow {:bead-animation (dart:core/Duration .milliseconds 400)
                    :bead-reset-interval (dart:core/Duration .milliseconds 20)
                    :bead-sound-interval (dart:core/Duration .milliseconds 10)}
             :fast {:bead-animation (dart:core/Duration .milliseconds 200)
                    :bead-reset-interval (dart:core/Duration .milliseconds 10)
                    :bead-sound-interval (dart:core/Duration .milliseconds 5)}
             ; :instant {:bead-animation dart:core/Duration.zero
             ;           :bead-reset-interval dart:core/Duration.zero
             ;           :bead-sound-interval dart:core/Duration.zero}
             })
