(ns acme.state
  (:require ["package:flutter/material.dart" :as m]))

;; FONTS

(def numeric-font "CourierPrimeSans")
(def default-font "Montserrat")
(def cabacus-font "Gaegu")

;; COLORS

; Nice place to look for colors: https://colorcodes.io/
; https://www.schemecolor.com/
(def colors
  (-> {:amber m.Colors/amber
       :medium-champagne (m/Color.fromARGB 255 247 237 163)
       :cotton-candy-pink (m/Color.fromARGB 255 255 188 217)
       :burlap-brown (m/Color.fromARGB 255 185 163 122)
       :pastel-green (m/Color.fromARGB 255 119 221 119)
       :light-purple (m/Color.fromARGB 255 197 180 227)
       :pastel-blue (m/Color.fromARGB 255 139 211 230)
       :pastel-red (m/Color.fromARGB 255 255 109 106)
       :pastel-grey (m/Color.fromARGB 255 207 207 196)
       :very-light-tangelo (m/Color.fromARGB 255 254 181 127)
       :pastel-turquoise (m/Color.fromARGB 255 153 197 196)
       :papaya-whip (m/Color.fromARGB 255 253 240 215)}
      (update-vals
       (fn [seed-color]
         {:seed-color seed-color
          :color-scheme (m/ColorScheme.fromSeed .seedColor seed-color)}))))

;; STYLE

(def frame-width 6)

(def bead-style-ratios {:narrow 3/2 :wide 5/3})

;; SIZES

(def sizes-base {:small  {:height 36 :rod-width 12}
                 :medium {:height 42 :rod-width 14}
                 :large  {:height 48 :rod-width 16}})

;; SPEED

(def speeds {:slow {:bead-animation (dart:core/Duration .milliseconds 400)
                    :bead-reset-interval (dart:core/Duration .milliseconds 20)
                    :bead-sound-interval (dart:core/Duration .milliseconds 10)}
             :fast {:bead-animation (dart:core/Duration .milliseconds 200)
                    :bead-reset-interval (dart:core/Duration .milliseconds 10)
                    :bead-sound-interval (dart:core/Duration .milliseconds 5)}
             ; :instant {:bead-animation dart:core/Duration.zero
             ;           :bead-reset-interval dart:core/Duration.zero
             ;           :bead-sound-interval dart:core/Duration.zero}
             })
